example.property: "I AM IN THE DEFAULT"

server.port: "8081"

spring.datasource.url: "jdbc:mysql://localhost:3306/microservice?characterEncoding=UTF-8"
spring.datasource.username: "root"
spring.datasource.password: "whatthehell"
spring.datasource.driver-class-name: "com.mysql.jdbc.Driver"

mybatis.type-aliases-package: "com.rdc.microservice.license.model"
mybatis.configuration.map-underscore-to-camel-case: true

redis.server: "redis"
redis.port: "6379"