spring:
  cloud:
    stream:
      bindings:
        input:
          destination: orgChangeTopic
          content-type: application/json
          group: licenseGroup
      kafka:
        binder:
          zkNodes: 192.168.111.130:2181
          brokers: 192.168.111.130:9092
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8084/user